// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let welcome = try? newJSONDecoder().decode(Welcome.self, from: jsonData)


/*
Generated by: https://app.quicktype.io/#l=swift
       Make sure select "Make all properties optional"
*/


import Foundation

// MARK: - Welcome
struct Posts: Codable {
    let posts: [Post]?
    let comments: [Comment]?
    let profile: Profile?
}

// MARK: - Comment
struct Comment: Codable {
    let id: Int?
    let body: String?
    let postID: Int?

    enum CodingKeys: String, CodingKey {
        case id, body
        case postID = "postId"
    }
}

// MARK: - Post
struct Post: Codable {
    let id: Int?
    let title: String?
}

// MARK: - Profile
struct Profile: Codable {
    let name: String?
}
